# Test configuration with SSL verification disabled and no hostname specified

server:
  name: mcp-k8s-server
  transport: sse
  port: 8003
  host: 127.0.0.1

kubernetes:
  # Path to kubeconfig file
  config_path: "~/.kube/config"
  
  # Kubernetes context to use
  context: ""
  
  # Default namespace
  namespace: default
  
  # Disable SSL verification (insecure)
  ssl_verify: false
  
  # Resource types to include
  resource_types:
    - pods
    - deployments
    - services
    - configmaps
    - secrets
    - nodes
    - namespaces

monitoring:
  # Disable monitoring for testing
  enabled: false
